name: Release

on:
  release:
    types:
      - created

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: pip install ordered-set nuitka

      - name: Generate files
        run: python build.py

      - name: Nuitka
        run: cd build && python -m nuitka main.py --standalone --assume-yes-for-downloads --lto=yes --company-name=EchoInMirror --product-name=EIMUtils --file-version=${{ github.event.release.tag_name }} --mingw64 --windows-icon-from-ico=../logo.ico
        shell: bash

      - name: Package
        run: |
          cd build
          mv main.dist EIMUtils
          mv EIMUtils/main.exe EIMUtils/EIMUtils.exe
          Compress-Archive -Path EIMUtils -DestinationPath EIMUtils.zip

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/EIMUtils.zip
          asset_name: EIMUtils-Windows.zip
          tag: ${{ github.event.release.tag_name }}

  build-macos-intel:
    runs-on: macos-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: pip3 install imageio

      - name: Generate files
        run: python build.py

      - name: Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: build/main.py
          onefile: false
          company-name: EchoInMirror
          product-name: EIMUtils
          file-version: ${{ github.event.release.tag_name }}
          macos-app-icon: logo512.png

      - name: Package
        run: |
          cd build
          mv main.dist EIMUtils
          mv EIMUtils/main.bin EIMUtils/EIMUtils
          zip -r EIMUtils.zip EIMUtils

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/EIMUtils.zip
          asset_name: EIMUtils-macos-x86_64.zip
          tag: ${{ github.event.release.tag_name }}

  build-macos-arm:
    runs-on: macos-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'arm64'

      - name: Install requirements
        run: pip3 install imageio

      - name: Generate files
        run: python build.py

      - name: Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: build/main.py
          macos-target-arch: arm64
          onefile: false
          company-name: EchoInMirror
          product-name: EIMUtils
          file-version: ${{ github.event.release.tag_name }}
          macos-app-icon: logo512.png
          macos-arch: arm64

      - name: Package
        run: |
          cd build
          mv main.dist EIMUtils
          mv EIMUtils/main.bin EIMUtils/EIMUtils
          zip -r EIMUtils.zip EIMUtils

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/EIMUtils.zip
          asset_name: EIMUtils-macOS.zip
          tag: ${{ github.event.release.tag_name }}
